#!/bin/bash
#set -x
typeset -a  pods=()

(( $# < 1 )) && {
    echo "USAGE: dopods <cmd> [[arg] ...]" > /dev/stderr
    echo " read a list of pods from stdin and exec cmd"  > /dev/stderr	
    exit -1
}

pods=( $(cat) )

for p in ${pods[@]}; do
    echo $p
    oc exec -i $p  -- $@
done

