#!/bin/bash
#set -x
set -x
typeset -r iperfbin=src/iperf-3.18/src/iperf3
typeset -r iperfport=12345
typeset -r ocdatadir=/tmp
typeset  datadir=ociperf_data
typeset -r ts=$(date +%d-%m-%y-%s)
datadir=${datadir}/$ts
typeset -r -a protocols=( tcp udp )
typeset -r par=128 mtu=1500
typeset -r -A bufsize=( ["tcp"]="128K" ["udp"]="1460" )


typeset -a  wrks=() pod=()
#wrks=( $(./ocwrks| grep mocr4pcc02 | head -2) )
wrks=( $(./ocwrks| grep mocr4pcc02) )

mkdir -p $datadir
log=$datadir/ociperf.log

function log()
{
    echo $EPOCHSECONDS ociperf : $@ | tee -a  $log
}

if (( $# > 0 )); then
    pods=( $(oc get pods --no-headers=true | cut -d' ' -f 1) )
else
    for wrk in ${wrks[@]}; do
	log "xfce4-terminal -e \"./occon $wrk\""
	xfce4-terminal -e "./occon --one-container=true $wrk"
    done 

    while (( ${#wrks[@]} != ${#pods[@]} )); do
	pods=( $(oc get pods | grep mocr4pcc02 | cut -d' ' -f 1) )
    done
fi

# wait till pods are ready;
for p in ${pods[@]}; do
    while ! oc describe pods $p > $datadir/$p.txt; do
	log "ERROR: failed to describe $p retry" 
	sleep 0.1;
    done
done

exit

for srv in ${pods[@]}; do
    log "oc cp $iperfbin $srv:/root/iperf3"
    ! oc cp $iperfbin $srv:/root/iperf3 && {
	log "ERROR: failed"
	exit -1
    }
done

for srv in ${pods[@]}; do
    read foo srvip < <(oc describe pods $srv | grep '^IP:')
    srvnode=${srv%%-*}
    log "server: $srv $srvip $srvnode"
   for clt in ${pods[@]}; do
       [[ $srv == $clt ]] && continue
       cltnode=${clt%%-*}
      for prot in ${protocols[@]}; do
	  if [[ $prot == udp ]]; then pflg='-u'; else pflg=''; fi
	  len=${bufsize[$prot]}
          srvlog="iperf_${prot}_srv_${mtu}_${len}_${par}_${srvnode}_${cltnode}.log"
	  cltlog="iperf_${prot}_clt_${mtu}_${len}_${par}_${srvnode}_${cltnode}.log"
	  log "prot:$prot mtu:$mtu bufsize:$len par:$par srvlog:$srvlog cltlog:$cltlog"
      	  log "START: $srv $clt"
	  log "oc exec $srv -- bash -c \"/root/iperf3 -s -p ${iperfport} -1 >$ocdatadir/$srvlog 2>&1 &\""
      	  oc exec $srv -- bash -c "/root/iperf3 -s -p ${iperfport} -1 >$ocdatadir/$srvlog 2>&1 &"
	  log "oc exec $clt -- bash -c \"/root/iperf3 -c $srvip -p $iperfport -l ${len} -P $par $pflg >$ocdatadir/$cltlog 2>&1\""
      	  oc exec $clt -- bash -c "/root/iperf3 -c $srvip -p $iperfport -l ${len} -P $par $pflg >$ocdatadir/$cltlog 2>&1"
	  log "$EPOCHSEONDS: END: $srv $clt"
	  sleep 0.1
      	  log "oc cp $srv:$ocdatadir/$srvlog $datadir/$srvlog"
	  oc cp $srv:$ocdatadir/$srvlog $datadir/$srvlog
	  log "oc cp $clt:$ocdatadir/$cltlog $datadir/$cltlog"
      	  oc cp $clt:$ocdatadir/$cltlog $datadir/$cltlog
      done  
   done 
done

for srv in ${pods[@]}; do
    log "oc pod delete $srv"
    oc delete pod  $srv &
done

wait 
