apiVersion: v1
kind: Pod
metadata:
  name: sr4n1
  namespace: default
spec:
  dnsPolicy: ClusterFirstWithHostNet #DNS not resolving MASTER_ADDR
  hostNetwork: true
  hostIPC: true
  nodeSelector: 
    kubernetes.io/hostname: moc-r4pcc02u25
  serviceAccountName: rdma
  containers:
  - image: quay.io/edge-infrastructure/nvidia-tools:0.1.5     # quay.io/jschless/gpu-tools:0.0.6 
    name: sr4n1
    securityContext:
      privileged: true
      capabilities:
        add: [ "IPC_LOCK", "SYS_ADMIN" ]
    resources:
      limits:
        nvidia.com/gpu:         4

      requests:
        nvidia.com/gpu:         4

